language: objective-c
osx_image: xcode611
sudo: false

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail && xcodebuild -project GooglePlacesAutocomplete.xcodeproj -scheme "GooglePlacesAutocomplete" -sdk iphonesimulator -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c
