language: objective-c
osx_image: beta-xcode6.3
sudo: false

cache:
  directories:
    - vendor/bundle

before_install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin

script:
  - bundle exec rake test
