language: objective-c
osx_image: xcode611
sudo: false

cache:
  directories:
    - vendor/bundle

before_install:
  - bundle install --path=vendor/bundle --binstubs=vendor/bin

script:
  - set -o pipefail && xcodebuild -workspace GooglePlacesAutocomplete.xcworkspace -scheme "GooglePlacesAutocompleteExample" -sdk iphonesimulator -destination 'name=iPhone 5S' -configuration Release ONLY_ACTIVE_ARCH=NO test | xcpretty -c
